title: Fabio Giardina # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 10+ years spanning academic research and industry across robotics, quantitative finance, and software engineering.
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
